SOURCES= app_trace.cpp	\
		 pli_iostream.cpp


INCS= 	app_trace.h					\
		dev_signal_generator.h		\
		user_choose_number.h		\
		user_choose_string.h		\
		user_menu.h					\
		user_time.h	\
		pli_iostream.h


MCU=atmega328p

LIB=pli

INSTALL_INC=$(MCU_INCLUDE)

include $(PLI_GENRULES)




