BIN = xx

SOURCES= main.cpp \
		../../../mega_timer0_hal.cpp \
		../../../mega_timer0_hwd.cpp \
		../../../mega_timer1_hal.cpp \
		../../../mega_timer1_hwd.cpp \
		 ../../../mega_UART_hal.cpp 


#F_CPU = 8000000UL
MCU = atmega328p
F_CPU = 1000000UL

include $(AVR_GENRULES)
