SOURCES= avr_sleep.cpp			\
		 avr_ADC_driver.cpp		\
		 avr_SPI_basic.cpp 		\
		 avr_SPI.cpp 			\
		 avr_timer0_basic.cpp	\
		 avr_timer0.cpp			\
		 avr_timer1_basic.cpp	\
		 avr_timer1.cpp			\
		 avr_UART.cpp


INCS= avr_ADC_basic.h		\
	avr_ADC_driver.h	\
	avr_atmega328p_cfg.h\
	avr_atmega_dev.h	\
	avr_atmega.h		\
	avr_cfg.h			\
	avr_interrupt.h		\
	avr_memory.h		\
	avr_micro.h			\
	avr_pin.h			\
	avr_port_basic.h	\
	avr_sleep.h			\
	avr_SPI_basic.h		\
	avr_SPI.h	\
	avr_time.h			\
	avr_timern_basic.h	\
	avr_timer0_basic.h	\
	avr_timer0.h\
	avr_timer1_basic.h	\
	avr_timer1.h\
	avr_timer2_basic.h	\
	avr_timer2.h\
	avr_TWI_basic.h		\
	avr_types.h				\
	avr_UART.h				\
	avr_UART_basic.h		\
	avr_UART_baud_rate.h	\
	avr_UART_iostream.h		\
	avr_watchdog.h			\
	avr_not_generic.h	


LIB=avr_$(F_CPU)
INSTALL_INC=$(MCU_INCLUDE)

include $(AVR_GENRULES)




