SOURCES= avr_sleep.cpp	\
		 avr_ADC_driver.cpp	\
		 avr_SPI_basic.cpp \
		 avr_SPI_generic.cpp \
		 avr_timer0_generic.cpp	\
		 avr_timer1_generic.cpp	\
		 avr_UART.cpp


INCS= dev_concepts.h	\
	avr_ADC_basic.h		\
	avr_ADC_driver.h	\
	avr_atmega328p_cfg.h\
	avr_atmega_dev.h	\
	avr_atmega.h		\
	avr_cfg.h			\
	avr_interrupt.h		\
	avr_memory.h		\
	avr_micro.h			\
	avr_pin.h			\
	avr_port_basic.h	\
	avr_sleep.h			\
	avr_SPI_basic.h		\
	avr_SPI_generic.h	\
	avr_time.h			\
	avr_timern_basic.h	\
	avr_timer0_basic.h	\
	avr_timer0_generic.h\
	avr_timer1_basic.h	\
	avr_timer1_generic.h\
	avr_timer2_basic.h	\
	avr_timer2_generic.h\
	avr_TWI_basic.h		\
	avr_types.h				\
	avr_UART.h				\
	avr_UART_basic.h		\
	avr_UART_baud_rate.h	\
	avr_UART_iostream.h		\
	avr_watchdog.h			\
	avr_not_generic.h	


LIB=avr_$(F_CPU)
INSTALL_INC=$(MCU_INCLUDE)

include $(AVR_GENRULES)




