BIN = xx

SOURCES=main.cpp	\
		../../avr_pin.cpp \
		../../alp_gen.cpp \
		../../avr_USART.cpp	#para depurar, incluy alp_gen y usart

ASM_SOURCES=../../avr_square_wave.S


MCU = atmega328p

include $(AVR_COMRULES)




