BIN = xx

SOURCES= main.cpp \
		 ../../../mega_SPI_hwd.cpp	\
		 ../../../mega_SPI_hal.cpp\
		 ../../../mega_debug_hwd.cpp\
		 ../../../mega_UART_hal.cpp

MCU = atmega328p
F_CPU = 1000000UL

include $(AVR_GENRULES)




