DIRS =  calculator	\
		cars		\
		clocks 		\
		datalogger	\
		dc_motor	\
		fatinspector	\
		IR_remote_control	\
		POV_toy		\
		sdinspector	\
		sensor		\
		util		



# Revisar:
#		signal_generator \
		stroboscope	\
		oscilloscope	\
		music		\

include $(MCU_RECRULES)


