SOURCES= app_trace.cpp	


INCS= 	app_trace.h					\
		dev_signal_generator.h		\
		user_choose_number.h		\
		user_choose_string.h		\
		user_menu.h					\
		user_time.h


LIB=libprj_$(F_CPU)
INSTALL_INC=$(MCU_INCLUDE)

include $(APP_GENRULES)




