BIN = xx

SOURCES= main.cpp \
		 ../../alp_gen.cpp \
		 ../../avr_pin.cpp \
		 ../../mcu_DHT22.cpp \
		 ../../avr_USART.cpp

ASM_SOURCES=../../avr_time.S


MCU = atmega328p

include $(AVR_COMRULES)




