// Copyright (C) 2023 Manuel Perez 
// mail: <manuel2perez@proton.me> 
// https://github.com/amanuellperez/mcu 
// 
// This file is part of the MCU++ Library. 
// 
// MCU++ Library is a free library: you can redistribute it and/or modify 
// it under the terms of the GNU General Public License as published by 
// the Free Software Foundation, either version 3 of the License, or 
// (at your option) any later version. 
// 
// This library is distributed in the hope that it will be useful, 
// but WITHOUT ANY WARRANTY; without even the implied warranty of 
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
// GNU General Public License for more details. 
// 
// You should have received a copy of the GNU General Public License 
// along with this program. If not, see <https://www.gnu.org/licenses/>. 

// This file was automatically generated by str2progmem 
 
#pragma once 
 
#ifndef __PRJ_STRINGS_H__ 
#define __PRJ_STRINGS_H__ 


constexpr mcu::Progmem_string<90> msg_hello   
	PROGMEM{"----------------------------------------\nSDCard\n----------------------------------------\n\n"};

constexpr mcu::Progmem_string<19> msg_main_no_sector_load 
	PROGMEM{"No sector in memory"};

constexpr mcu::Progmem_string<27> msg_main_sector_load 
	PROGMEM{"Sector in memory. Address: "};

constexpr mcu::Progmem_string<86> msg_main_menu	
	PROGMEM{"\n----\n1. Read status register\n2. Read sector\n3. Read sector in [a, b]\n4. Write sector\n"};

constexpr mcu::Progmem_string<23> msg_main_read	
	PROGMEM{"Read\n----\nblock_size = "};

constexpr mcu::Progmem_string<7> msg_address	
	PROGMEM{"Address"};

constexpr mcu::Progmem_string<8> msg_read_ok 
	PROGMEM{"read OK."};

constexpr mcu::Progmem_string<18> msg_read_sector_from 
	PROGMEM{"first byte to show"};

constexpr mcu::Progmem_string<23> msg_read_sector_size 
	PROGMEM{"number of bytes to show"};

constexpr mcu::Progmem_string<38> msg_read_sector_from_to_big 
	PROGMEM{"Error: first byte has to be less than "};

constexpr mcu::Progmem_string<18> msg_read_sector_size_to_big 
	PROGMEM{"Error: size to big"};

constexpr mcu::Progmem_string<12> msg_main_write  
	PROGMEM{"Write\n-----\n"};


 
#endif

