# -----
# Fuses
# -----
# Valores por defecto para atmega328
LFUSE_DEFAULT = 0x62
HFUSE_DEFAULT = 0xD9
EFUSE_DEFAULT = 0xFF

LFUSE_FAST_FUSE = 0xE2
LFUSE_CLOCK_OUTPUT_FUSE = 0xA2
LFUSE_CLOCK_OUTPUT_DIVIDE_BY_8 = 0x22
LFUSE_SET_EXTERNAL_CRYSTAL_8MHZ = 0x7F

HFUSE_EEPROM_SAVE_FUSE = 0xD7


