BIN = xx

SOURCES= main.cpp 	\
		 ../../../avr_timer0_basic.cpp	\
		 ../../../avr_timer0.cpp	\
		 ../../../avr_timer1_basic.cpp \
		 ../../../avr_timer1.cpp \
		 ../../../avr_UART.cpp


MCU = atmega328p

include $(AVR_GENRULES)




