BIN = xx

SOURCES= prj_main.cpp 		\
		prj_receive.cpp		\
		prj_transmit.cpp	\
		prj_run.cpp			\
		ptrain_receive.cpp	\
		transmit.cpp		\
		IR_NEC_protocol.cpp	\
		IR_NEC_print.cpp	\
		IR_NEC_transmit.cpp	


MCU = atmega328p

F_CPU=8000000UL

include $(APP_GENRULES)




