BIN = xx

SOURCES= prj_main.cpp 		\
		prj_receive.cpp		\
		prj_transmit.cpp	\
		prj_research.cpp	\
		prj_run.cpp			\
		prj_isr.cpp			\
		NEC_protocol.cpp


MCU = atmega328p

F_CPU=8000000UL

include $(APP_GENRULES)




