BIN = xx

SOURCES= main.cpp 		\
		receive_pulses.cpp	\
		transmit_pulses.cpp	\
		print_data.cpp		\
		transmit_data.cpp		\
		IR_NEC_protocol.cpp		\
		run.cpp


MCU = atmega328p

F_CPU=8000000UL

include $(APP_GENRULES)




