DIRS = 	BMP280			\
		BME280			\
		CD4017B			\
		DS1307			\
		DHT11			\
		EEPROM_25LC256	\
		keypad			\
		keyrow			\
		led				\
		HD44780			\
		push_button		\
		74HC595			\
		sdcard

# Revisar
#	DHT22\
	matrix_8x8\
	matrix_leds_max7219\
	pololu_A4988\
	TMP36\
	LM75				\
	pot_MCP4231			\

include $(MCU_RECRULES)


