DIRS = iostream\
	servidor

# Estos se compilan con g++, no con avr-g++!!
# Son pruebas automáticas para hechas en el ordenador
# y no en el avr:
# baud_rate\

# Esta no es automática. Se compila con g++
#clientes\

include $(MCU_RECRULES)


