BIN = xx

SOURCES= main.cpp \
		 ../../alp_gen.cpp \
		 ../../avr_pin.cpp \
		 ../../avr_USART.cpp\
		 ../../avr_SPI.cpp


#ASM_SOURCES=../avr_time.S	\
			../avr_square_wave.S


MCU = atmega328p

include $(AVR_COMRULES)




