# TODO: si se implementan más micros, 
# crear un directorio fuera `generic` para probar todos los dispositivos
# genéricos sea cual sea el micro.
DIRS = ADC	\
	cfg		\
	generic_timer\
	interrupt\
	memory	\
	pin		\
	port	\
	sleep	\
	SPI		\
	timer0	\
	timer1	\
	TWI		\
	USART 



include $(MCU_RECRULES)


