SOURCES= dev_one_wire.cpp

INCS= 	dev_clocks.h	\
		dev_cycle.h		\
		dev_miniclock.h	\
		dev_one_wire.h	\
		dev_train_of_pulses.h	\
		dev_TWI_master.h\
		dev_TWI_master_ioxtream.h	\
		dev_TWI_slave.h


LIB=mcu1_$(F_CPU)
INSTALL_INC=$(MCU_INCLUDE)

include $(MCU1_GENRULES)




