SOURCES= mcu_one_wire.cpp

INCS= 	mcu_clock.h					\
		mcu_concepts.h				\
		mcu_cycle.h					\
		mcu_miniclock.h				\
		mcu_one_wire.h				\
		mcu_pin.h					\
		mcu_train_of_pulses.h		\
		mcu_TWI_master.h			\
		mcu_TWI_master_ioxtream.h	\
		mcu_TWI_slave.h


LIB=mcu1_$(F_CPU)
INSTALL_INC=$(MCU_INCLUDE)

include $(MCU1_GENRULES)




