SOURCES= 

INCS= 	rom_font_alagard_13x15_cr.h					\
		rom_font_DePixelBreit_12x10_cr.h			\
		rom_font_DePixelBreitFett_23x13_cr.h		\
		rom_font_DePixelHalbfett_11x13_cr.h			\
		rom_font_DePixelIllegible_8x8_cr.h			\
		rom_font_DePixelKlein_10x10_cr.h			\
		rom_font_DePixelSchmal_10x11_cr.h			\
		rom_font_dogica_8x8_cr.h					\
		rom_font_dogicabold_8x8_cr.h				\
		rom_font_dogica_number_5x7_cr.h				\
		rom_font_dogicapixel_7x8_cr.h				\
		rom_font_dogicapixelbold_8x8_cr.h			\
		rom_font_HomeVideo-Regular_10x14_cr.h		\
		rom_font_mai10_10x14_cr.h					\
		rom_font_Minecraft_14x16_cr.h				\
		rom_font_PerfectDOSVGA437_8x15_cr.h			\
		rom_font_PerfectDOSVGA437Win_8x15_cr.h		\
		rom_font_rainyhearts_11x13_cr.h				\
		rom_font_RetroGaming_11x13_cr.h				\
		rom_font_upheavtt_13x14_cr.h				\
		rom_font_VCR_12x17_cr.h				\
		rom_glyphs_5x8.h

LIB=rom
INSTALL_INC=$(MCU_INCLUDE)

include $(ROM_GENRULES)




