SOURCES= atd_bcd.cpp		\
		 atd_char.cpp		\
		 atd_cstddef.cpp 	\
		 atd_cstring.cpp	\
		 atd_double.cpp		\
		 atd_test.cpp		\
		 atd_time.cpp

INCS= atd_algorithm.h	\
	  atd_array.h		\
	atd_ascii.h			\
	atd_bcd.h			\
	atd_bit.h 			\
	atd_bounded.h		\
	atd_cast.h			\
	atd_char.h			\
	atd_cmath.h			\
	atd_concepts.h		\
	atd_coordinates.h	\
	atd_crc.h			\
	atd_cstddef.h		\
	atd_cstring.h		\
	atd_decimal.h		\
	atd_double.h		\
	atd_float.h			\
	atd_geometry_2d.h	\
	atd_iobxtream.h		\
	atd_istream.h		\
	atd_iterator.h		\
	atd_magnitude.h		\
	atd_math.h 			\
	atd_memory.h		\
	atd_metronome.h		\
	atd_minifloat.h		\
	atd_names.h			\
	atd_ostream.h		\
	atd_percentage.h	\
	atd_pwm.h			\
	atd_ratio.h			\
	atd_rom.h			\
	atd_static.h		\
	atd_string.h		\
	atd_test.h			\
	atd_time.h			\
	atd_type_traits.h	\
	atd_units.h

LIB=atd


include $(ATD_GENRULES)


