SOURCES= atd_bcd.cpp		\
		 atd_cstddef.cpp 	\
		 atd_cstring.cpp	\
		 atd_time.cpp

INCS= atd_algorithm.h	\
	atd_ascii.h			\
	atd_bcd.h			\
	atd_bit.h 			\
	atd_buffer.h		\
	atd_cast.h			\
	atd_cstddef.h		\
	atd_cstring.h		\
	atd_decimal.h		\
	atd_eng_magnitude.h	\
	atd_istream.h		\
	atd_magnitude.h		\
	atd_math.h 			\
	atd_memory.h		\
	atd_metronome.h		\
	atd_ostream.h		\
	atd_ratio.h			\
	atd_static.h		\
	atd_time.h			\
	atd_types.h			\
	atd_type_traits_basic.h\
	atd_type_traits_more.h\
	atd_type_traits.h	\
	atd_units.h

LIB=atd


include $(ATD_GENRULES)


