SOURCES= atd_cstddef.cpp 	\
		 atd_cstring.cpp	\
		 atd_time.cpp

INCS= atd_algorithm.h	\
	atd_ascii.h			\
	atd_bit.h 			\
	atd_buffer.h		\
	atd_cast.h			\
	atd_cstddef.h		\
	atd_cstring.h		\
	atd_decimal.h		\
	atd_istream.h		\
	atd_ostream.h		\
	atd_math.h 			\
	atd_register.h		\
	atd_time.h			\
	atd_type_traits.h

LIB=atd


include $(ATD_GENRULES)
#include $(ALP_COMPRULES)


