DIRS = algorithm	\
	   ascii		\
		bit			\
		buffer		\
		cast		\
		cstddef		\
		cstring		\
		decimal		\
		magnitude	\
		math		\
		time		\
		type_traits


# TODO: las pruebas de iostream no son automaticas
# iostream	\


include $(CPP_RECRULES)


