BIN = xx

SOURCES= 	prj_main.cpp 		\
			prj_init.cpp		\
			prj_interrupt.cpp	\
			prj_menu.cpp		\
			prj_ds18b20.cpp		\
			prj_time.cpp


MCU = atmega328p

#F_CPU=8000000UL

include $(PRJ_GENRULES)




