BIN = xx

SOURCES= prj_main.cpp 		\
		 prj_clone.cpp		\
		prj_receive.cpp		\
		prj_transmit.cpp	\
		prj_research.cpp	\
		prj_run.cpp			\
		prj_isr.cpp			\
		os.cpp				\
		dev_NEC_protocol.cpp


MCU = atmega328p
F_CPU = 1000000UL

# Funciona bien a 1 MHz
#F_CPU=8000000UL

include $(PRJ_GENRULES)




