SOURCES= dev_BMP280_basic.cpp	\
		 dev_BME280_basic.cpp	\
		 dev_DS1307_basic.cpp	


INCS= 	dev_BME280_basic.h		\
		dev_BMP280_basic.h		\
		dev_counter_CD4017B.h	\
		dev_DS1307_basic.h		\
		dev_DS1307_clock.h		\
		dev_EEPROM_25LC256_basic.h		\
		dev_glyphs.h			\
		dev_keyboard_analog.h	\
		dev_keyboard_code.h		\
		dev_keypad.h			\
		dev_keyrow.h			\
		dev_LCD_generic.h		\
		dev_LCD_HD44780_basic.h		\
		dev_LCD_HD44780_basic.tcc		\
		dev_LCD_HD44780_charset.h		\
		dev_LCD_HD44780_generic.h		\
		dev_LCD_HD44780.h		\
		dev_led.h				\
		dev_LM75.h				\
		dev_matrix_led_max7219.h		\
		dev_pot_MCP4231.h		\
		dev_push_button.h		\
		dev_register_74HC595_SPI.h		\
		dev_TMP36.h				\
		dev_TWI_memory_type.h		\
		not_generic.h		

#		dev_DHT22.h\


LIB=dev0_$(F_CPU)
INSTALL_INC=$(MCU_INCLUDE)

include $(DEV0_GENRULES)




