SOURCES= app_trace.cpp		\
		 dev_clocks.cpp	


INCS= 	app_trace.h					\
		dev_clocks.h				\
		user_choose_number.h		\
		user_choose_string.h		\
		user_menu.h					\
		user_time.h


LIB=app_$(F_CPU)
INSTALL_INC=$(MCU_INCLUDE)

include $(DEV_GENRULES)




