BIN = xx

SOURCES= main.cpp

MCU = atmega4809


# make write_fuses: 
# a 16 MHz
FUSE2=0x01
# a 20 MHz
#FUSE2=0x02

F_CPU = 2666667UL # 16 MHz / 6
#F_CPU = 3333333UL # 20 MHz / 6

include $(AVR_GENRULES)




