DIRS =  blink		\
		calculator	\
		clocks 		\
		IR_remote_control	\
		music		\
		POV_toy		\
		sensor		\
		util		



# Revisar:
#		signal_generator \
		stroboscope	\
		oscilloscope

include $(MCU_RECRULES)


