BIN = xx

SOURCES= main.cpp 			\
		main_run.cpp 		\
		cfg.cpp 			\
		signal_generator.cpp \
		sound_generator.cpp	\
		sw_generator.cpp	


MCU = atmega328p
F_CPU = 1000000UL

include $(PRJ_GENRULES)




