// Copyright (C) 2023 Manuel Perez 
// mail: <manuel2perez@proton.me> 
// https://github.com/amanuellperez/mcu 
// 
// This file is part of the MCU++ Library. 
// 
// MCU++ Library is a free library: you can redistribute it and/or modify 
// it under the terms of the GNU General Public License as published by 
// the Free Software Foundation, either version 3 of the License, or 
// (at your option) any later version. 
// 
// This library is distributed in the hope that it will be useful, 
// but WITHOUT ANY WARRANTY; without even the implied warranty of 
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
// GNU General Public License for more details. 
// 
// You should have received a copy of the GNU General Public License 
// along with this program. If not, see <https://www.gnu.org/licenses/>. 

// This file was automatically generated by str2rom 
 
#pragma once 
 
#ifndef __DEV_STRINGS_H__ 
#define __DEV_STRINGS_H__ 


constexpr mcu::ROM_string<3> msg_yes	
	PROGMEM{"yes"};

constexpr mcu::ROM_string<2> msg_no	
	PROGMEM{"no"};

constexpr mcu::ROM_string<2> msg_ok	
	PROGMEM{"ok"};

constexpr mcu::ROM_string<24> msg_press_key_to_continue   
	PROGMEM{"Press a key to continue\n"};

constexpr mcu::ROM_string<32> msg_line    
	PROGMEM{"-------------------------------\n"};


 
#endif

