DIRS = 	25LC256			\
		74HC595			\
		A4988			\
		BME280			\
		BMP280			\
		CD4017B			\
		DHT11			\
		DHT22			\
		DS1307			\
		DS18B20			\
		HCSR04			\
		HD44780			\
		joystick		\
		keypad			\
		keyrow			\
		L298N			\
		led				\
		MAX7219			\
		push_button		\
		SDD1306

# TODO: revisar
#		sdcard			\






# Revisar
#	matrix_8x8\
	OV7670\
	pot_MCP4231\
	TMP36\
	LM75				\
	MCP4231			\
	keyboard_analog	\
	ULN2003

include $(MCU_RECRULES)


