DIRS = 	25LC256			\
		BMP280			\
		BME280			\
		CD4017B			\
		DHT11			\
		DHT22			\
		DS1307			\
		DS18B20			\
		HD44780			\
		keypad			\
		keyrow			\
		led				\
		push_button		\
		74HC595			\
		sdcard

# Revisar
#	matrix_8x8\
	MAX7219\
	pololu_A4988\
	TMP36\
	LM75				\
	MCP4231			\
	keyboard_analog

include $(MCU_RECRULES)


