DIRS = 	algorithm	\
	   	array		\
	   	ascii		\
		bounded		\
	   	bcd			\
		bit			\
		cast		\
		char		\
		cmath		\
		concepts	\
		crc			\
		cstddef		\
		cstring		\
		decimal		\
		double		\
		float		\
		geometry_2d	\
		iobxtream	\
		istream		\
		iterator	\
		magnitude	\
		math		\
		memory		\
		metronome	\
		minifloat	\
		names		\
		ostream		\
		percentage	\
		pwm			\
		ratio		\
		static		\
		string		\
		time		\
		type_traits	\
		units


# TODO: las pruebas de iostream no son automaticas
# iostream	\
	


include $(CPP_RECRULES)


