DIRS = algorithm	\
	   array		\
	   ascii		\
	   bcd			\
		bit			\
		buffer		\
		cast		\
		cstddef		\
		cstring		\
		decimal		\
		eng_magnitude\
		iobxtream	\
		magnitude	\
		math		\
		metronome	\
		ratio		\
		static		\
		time		\
		types		\
		type_traits	\
		units


# TODO: las pruebas de iostream no son automaticas
# iostream	\


include $(CPP_RECRULES)


