# TODO: si se implementan más micros, 
# crear un directorio fuera `generic` para probar todos los dispositivos
# genéricos sea cual sea el micro.

DIRS = \
		clock		\
		hello_world	\
		pin			\
		spi			\
		usart


# TWI: el test de TWI está dentro de mcu.
#      Probarlo directamente con TWI_master/TWI_slave


include $(MCU_RECRULES)


