# TODO: si se implementan más micros,
# 		sacar el directorio hal fuera. Debería de ser genérico.

DIRS = \
		clock		\
		hal			\
		hello_world	\
		pin			\
		spi			\
		usart


# TWI: el test de TWI está dentro de mcu.
#      Probarlo directamente con TWI_master/TWI_slave


include $(MCU_RECRULES)


