DIRS = CD4017B			\
	EEPROM_25LC256		\
	EEPROM_iostream		\
	EEPROM_lineal		\
	HD44780				\
	led					\
	LM75				\
	pot_MCP4231			\
	push_button			\
	system_clock		\
	user_choose_number	\
	user_menu			\
	user_time

# Revisar
#74HC595\
	DHT22\
	matrix_8x8\
	matrix_leds_max7219\
	pololu_A4988\
	speaker\
	TMP36\

include $(MCU_RECRULES)


