DIRS = 	BMP280			\
		BME280			\
		CD4017B			\
		DS1307			\
		EEPROM_25LC256	\
		EEPROM_iostream	\
		EEPROM_lineal	\
		HD44780			\
		keyboard		\
		led				\
		push_button		\
		system_clock	\
		user_choose_number	\
		user_choose_string \
		user_time

# Revisar
#74HC595\
	DHT22\
	matrix_8x8\
	matrix_leds_max7219\
	pololu_A4988\
	speaker\
	TMP36\
	LM75				\
	pot_MCP4231			\

include $(MCU_RECRULES)


