BIN = xx

SOURCES= 	hwd_init.cpp			\
			hwd_interrupt.cpp		\
			prj_init.cpp			\
			prj_main.cpp			\
			prj_measure_speed.cpp	\
			prj_speed_control.cpp	\
			prj_turn.cpp	

MCU = atmega328p

#F_CPU=8000000UL

include $(PRJ_GENRULES)




