BIN = xx

SOURCES= main.cpp	

USER_CXXFLAGS=-save-temps -fverbose-asm

# para probar
#F_CPU = 8000000UL

#MCU = atmega328p
MCU = atmega4809
F_CPU = 1000000UL	# pruebo los dos a 1MHz

include $(HWD_GENRULES)




