DIRS = algorithm\
	array		\
	bit			\
	char_traits	\
	cmath		\
	cstddef		\
	cstdio		\
	iostream	\
	iterator	\
	numeric		\
	ratio		\
	sizeof_txt	\
	type_traits	\
	tuple		\
	utility


# initializer_list	<--- has to compile with avr-gcc!!!

include $(CPP_RECRULES)


