BIN = xx

SOURCES= main.cpp \
		 ../../../mega_sleep.cpp	\
		 ../../../mega_debug.cpp \
		 ../../../mega_UART.cpp


MCU = atmega328p

#F_CPU=8000000L
F_CPU=1000000L
#USER_LIBS=mtd atd 

include $(AVR_GENRULES)
