BIN = xx

SOURCES= main.cpp 	\
		 ../../../mega_hwd_timer0.cpp	\
		 ../../../mega_timer0.cpp	\
		 ../../../mega_hwd_timer1.cpp \
		 ../../../mega_timer1.cpp \
		 ../../../mega_UART.cpp


MCU = atmega328p
F_CPU = 1000000UL

include $(AVR_GENRULES)




