SOURCES= 

INCS= 	dev_dc_motor.h			\
		dev_EEPROM_iostream.h	\
		dev_EEPROM_lineal.h		\
		dev_LCD_big_digits.h	\
		dev_LCD_font_2x1.h		\
		dev_LCD_font_2x2.h		\
		dev_LCD_font_2x3.h		\
		dev_LCD_font_3x3.h		\
		dev_LCD_font_4x3.h		\
		dev_LCD_ostream.h		\
		dev_LCD_screen.h		\
		dev_LCD_screen.tcc		\
		dev_LCD_terminal.h		\
		dev_LCD_terminal.tcc	\
		dev_square_wave.h


LIB=logic_$(F_CPU)
INSTALL_INC=$(MCU_INCLUDE)

include $(LOGIC_GENRULES)




