SOURCES= avr_SPI.cpp 	\
		 avr_TWI.cpp	


INCS= avr_ADC.h		\
	avr_array.h		\
	avr_atmega328p.h\
	avr_cfg.h		\
	avr_clock.h		\
	avr_dpin.h		\
	avr_interrupt.h	\
	avr_pin.h		\
	avr_port.h		\
	avr_SPI.h		\
	avr_time.h		\
	avr_timer0.h	\
	avr_timer1_tr.h	\
	avr_TWI.h		\
	avr_USART.h		\
	avr_USART_tr.h		\
	avr_USART_baud_rate.h	\
	avr_USART_iostream.h

LIB=avr_$(F_CPU)
INSTALL_INC=$(MCU_INCLUDE)

include $(AVR_GENRULES)




