SOURCES= avr_SPI.cpp


INCS= avr_ADC.h		\
	avr_atmega328p.h\
	avr_cfg.h		\
	avr_interrupt.h	\
	avr_pin.h		\
	avr_port.h		\
	avr_SPI.h		\
	avr_time.h		\
	avr_timer0_basic.h	\
	avr_timer1_basic.h	\
	avr_TWI.h		\
	avr_TWI_basic.h	\
	avr_TWI_master.h\
	avr_TWI_slave.h	\
	avr_TWI_master_ioxtream.h\
	avr_TWI_master_memory_type.h\
	avr_UART.h		\
	avr_UART_basic.h		\
	avr_UART_baud_rate.h	\
	avr_UART_iostream.h	\
	mcu_cfg.h


LIB=avr_$(F_CPU)
INSTALL_INC=$(MCU_INCLUDE)

include $(AVR_GENRULES)




