SOURCES= avr_SPI_basic.cpp \
		 avr_sleep.cpp


INCS= avr_ADC_basic.h	\
	avr_atmega328p_cfg.h\
	avr_atmega.h		\
	avr_cfg.h			\
	avr_interrupt.h		\
	avr_memory.h		\
	avr_pin.h			\
	avr_port.h			\
	avr_sleep.h			\
	avr_SPI_basic.h		\
	avr_time.h			\
	avr_timern_basic.h	\
	avr_timer0_basic.h	\
	avr_timer0_generic.h\
	avr_timer1_basic.h	\
	avr_timer1_generic.h\
	avr_TWI.h			\
	avr_TWI_basic.h		\
	avr_TWI_master.h	\
	avr_TWI_slave.h		\
	avr_TWI_master_ioxtream.h\
	avr_types.h				\
	avr_UART.h				\
	avr_UART_basic.h		\
	avr_UART_baud_rate.h	\
	avr_UART_iostream.h	


LIB=avr_$(F_CPU)
INSTALL_INC=$(MCU_INCLUDE)

include $(AVR_GENRULES)




