SOURCES=


INCS=\
	mega0.h			\
	mega0_cfg.h		\
	mega0_clock.h	\
	mega0_import_avr.h	\
	mega0_micro.h	\
	mega0_pin.h

MCU=atmega4809

LIB=micro

# de momento compilo para la frecuencia por defecto
#F_CPU=2666667UL
F_CPU=1000000UL

INSTALL_INC=$(MCU_INCLUDE)

include $(AVR_GENRULES)




