SOURCES=


INCS=\
	mega0_cfg.h		\
	mega0_clock.h	\
	mega0.h			\
	mega0_pin.h

MCU=atmega4809

LIB=micro

# de momento compilo para la frecuencia por defecto
F_CPU=2666667UL

INSTALL_INC=$(MCU_INCLUDE)

include $(AVR_GENRULES)




