SOURCES= std_basic_ios.cpp 	\
		 std_streambuf.cpp	\
		 std_istream.cpp	\
		 std_ostream.cpp

INCS= std_cstdio.h		\
	std_cmath.h			\
	std_sizeof_txt.h	\
	std_algorithm.h		\
	std_array.h			\
	std_basic_ios.h		\
	std_bit.h			\
	std_char_traits.h	\
	std_chrono.h		\
	std_config.h		\
	std_climits.h		\
	std_cstddef.h		\
	std_cstdint.h		\
	std_cstdlib.h		\
	std_ctime.h			\
	std_initializer_list.h	\
	std_ios_base.h		\
	std_ios.h			\
	std_iosfwd.h		\
	std_ios_types.h		\
	std_iostream.h		\
	std_iomanip.h		\
	std_istream.h		\
	std_iterator.h		\
	std_limits.h		\
	std_numeric.h		\
	std_ostream.h		\
	std_ratio.h			\
	std_streambuf.h		\
	std_cstring.h		\
	std_string.h		\
	std_tuple.h			\
	std_type_traits.h	\
	std_utility.h		\
	algorithm	\
	array		\
	bit			\
	chrono		\
	climits		\
	cmath		\
	cstddef 	\
	cstdint		\
	cstdlib		\
	cstring		\
	ctime		\
	initializer_list	\
	iomanip		\
	ios			\
	iosfwd		\
	iostream	\
	istream		\
	iterator	\
	limits		\
	numeric		\
	ostream		\
	ratio		\
	streambuf	\
	tuple		\
	type_traits	\
	utility


LIB=std

include $(STD_GENRULES)


