# TODO: si se implementan más micros, 
# crear un directorio fuera `generic` para probar todos los dispositivos
# genéricos sea cual sea el micro.

DIRS = \
	cfg		\
	generic_timer\
	memory	\
	pin		\
	port	\
	sleep	\
	SPI		\
	timer0	\
	timer1	\
	timer2	\
	TWI		\
	USART 

# Revisar:  ADC	


include $(MCU_RECRULES)


