# TODO: si se implementan más micros, 
# crear un directorio fuera `generic` para probar todos los dispositivos
# genéricos sea cual sea el micro.

DIRS = \
	automatic
	ADC		\
	cfg		\
	generic_timer\
	memory	\
	pin		\
	port	\
	sleep	\
	SPI		\
	timer0	\
	timer1	\
	timer2	\
	USART 


# TWI: el test de TWI está dentro de mcu.
#      Probarlo directamente con TWI_master/TWI_slave


include $(MCU_RECRULES)


